apiVersion: v1
kind: Pod
metadata: 
  name: pod
spec:
  containers:
  - name: tomcat
    image: tomcat
    volumeMounts:
    - name: hostpath-volume
      mountPath: /usr/local/tomcat/logs
    
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/logs  # directory location on host
      type: Directory   # this field is optional