- name: deploy nginx
  template:
    src: ../templates/mysite.j2
    dest: /etc/nginx/sites-enabled/mysite
  tags: configuration, installation
  notify: restart nginx

- name: remove defaults
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags: configuration, installation