version: "3"
services:
  simplilearn:
    image: thespiritman/simplilearn-devops-project1-angular:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
  
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    deploy:
      replicas: 6 
      restart_policy:
        condition: on-failure
      
  nosk:
    image: thespiritman/noskofficial_website:latest
    ports:
      - "8082:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure