- hosts: webservers
  become: true
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello World!"
  tasks:
    - name: ensure apache2 is at latest version
      apt:
        name: apache2
        state: latest
    
    - name: write the apache2 ports.conf config file
      template:
        src: ../templates/ports.conf.j2
        dest: /etc/apache2/ports.conf
      notify: 
      - restart apache2

    - name: write a basic index.html file
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
      notify: 
      - restart apache2
    
    - name: ensure apache2 is running
      service:
        name: apache2
        state: started
    
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

- hosts: databases
  become: true
  tasks:
    - name: install mysql-server latest version
      apt:
        name: mysql-server
        state: present
    
    - name: ensure mysql-server is running
      service:
        name: mysql
        state: started