apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods
  labels: 
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: knode2
      containers:
      - image: nginx
        name: pod2