apiVersion: v1
kind: Pod
metadata:
  name: rp-nginx-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
#     tcpSocket:
#       port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
