apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
      - name: contd1
        image: thespiritman/noskofficial_website
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          httpGet:
            port: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: rp-svc
spec:
  type: ClusterIP
  selector:
    role: web
  ports:
  - name: http
    port: 80
    targetPort: 8080
