apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - name: tomcat-with-pvc
    image: tomcat
    volumeMounts:
    - name: pv1
      mountPath: /usr/local/tomcat/logs
  volumes:
  - name: pv1
    persistentVolumeClaim:
      claimName: my-pvc