apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      nodeSelector:
        color: "green"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80