- name: install apache2 latest version
  apt:
    name: apache2
    state: latest

- name: write apache2 ports.conf file
  template:
    src: ../templates/ports.conf.j2
    dest: /etc/apache2/ports.conf

- name: write basic index.html file
  template:
    src: ../templates/index.html.j2
    dest: /var/www/html/index.html
  notify: 
  - restart apache2

- name: ensure apache2 is running
  service:
    name: apache2
    state: started