apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      nodeName: knode2
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
