apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
    owner: gc
    type: db
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
