apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deploy
  labels:
    app: nginx
    type: nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      type: nfs
  template:
    metadata:
      labels:
        app: nginx
        type: nfs
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nfs-vol
          mountPath: /var/log/nginx/

      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-pvc