apiVersion: v1
kind: Secret
metadata:
  name: ex-1
type: Opaque
data:
  username: VGhlU3Bpcml0TWFu
  password: a3ViZXJuZXRlcy1kZW1v

--- 

apiVersion: v1
kind: Pod
metadata:
  name: secret-ex1-pod
spec:
  containers:
  - name: cont1
    image: nginx
    volumeMounts:
    - name: myvol
      mountPath: "/apps/secrets"
      readOnly: true
  volumes:
  - name: myvol
    secret:
      secretName: ex-1