apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-html
data:
  index.html: |
    <h1> Hello Dev Env ConfigMap </h1>
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-html
data:
  index.html: |
    <h1>Hello Prod ConfigMap</h1>

---
apiVersion: v1
kind: Pod
metadata:
  name: cm-prod-ex1
spec:
  containers:
  - name: nginx-dev
    image: nginx
    ports:
    - containerPort: 80
    # to use ConfigMap as files in a volume
    volumeMounts:
    - name: html-from-dev-cm
      mountPath: /usr/share/nginx/html/
      readOnly: true

  volumes:
  - name: html-from-dev-cm
    configMap:
      name: dev-html
  - name: html-from-prod-cm
    configMap:
      name: prod-html