apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-test-deploy
  namespace: test
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: db
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: 64Mi
            cpu: 125m
          limits:
            memory: 128Mi
            cpu: 250m