apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test 
  
--- 

apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-rq
  namespace: test  
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 0.5Gi
    limits.cpu: "0.8"
    limits.memory: 1Gi