- hosts: webservers
  become: true
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello world!"
  roles:
    - roles/apache2
  tags: webservers

- hosts: proxy
  become: true
  roles:
    - roles/nginx
  tags: proxy

- hosts: databases
  become: true
  roles:
    - roles/database
  tags: databases