apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: demo-counter
    image: thespiritman/demo-counter-app:latest
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 500m
  - name: nosk
    image: thespiritman/noskofficial_website:latest
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 500m
