- hosts: webservers
  become: true
  roles:
    - apache2
    - common
  tags: web

- hosts: proxy
  become: true
  roles:
    - common
    - nginx
  tags: proxy

- hosts: database
  become: true
  roles:
    - common
    - mysql
  tags: database