apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: bash
    image: bash

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-deploy
  labels:
    app: collection
spec:
  replicas: 5
  selector:
    matchLabels:
      app: collection
  template:
    metadata:
      labels:
        app: collection
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: tomcat
        image: tomcat
        ports: 
        - containerPort: 8080
    
---
apiVersion: v1
kind: Service
metadata:
  name: col-svc
  labels:
    app: collection
spec:
  type: NodePort
  selector:
    app: collection
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32222

  - name: tomcat
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32223