apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcatrc
spec:
  replicas: 3
  selector:
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcatsvc
  labels:
    app: tomcatapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: tomcat
