version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    deploy:
      mode: global
      restart_policy: 
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    depends_on:
     - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    deploy:
      replicas: 2
      restart_policy: 
       condition: on-failure
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: