apiVersion: v1
kind: Pod
metadata:
  name: lp-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80 #800
      initialDelaySeconds: 5
      periodSeconds: 5
