apiVersion: v1
kind: Pod
metadata:
  name: lp-ex2
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        port: 80
      initialDelaySeconds: 12
      periodSeconds: 5
      timeoutSeconds: 3
 
  - name: tomcat
    image: tomcat
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
