apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: id
spec:
  replicas: 3
  minReadySeconds: 5  # wait for 45sec before pod is ready going to next
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: id
  template:
    metadata:
      labels:
        app: id
    spec:
      containers:
      - name: app
        image: thespiritman/container-id:v1  # change between v1 and v2  
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: rolling-svc
spec:
  type: NodePort
  selector:
    app: id
  ports:
  - port: 3000
    targetPort: 3000 
    protocol: TCP
    nodePort: 30003