apiVersion: v1
kind: Pod
metadata:
  name: init-count-ex1
spec:
  containers:
  - name: nginx
    image: nginx
    restartPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html/

  initContainers:
  - name: alpine
    image: alpine
    command:
    - sh
    - "-c"
    - |
      mkdir -p /init-contd && \
      touch /init-contd/index.html && \
      echo "Added init Count Demo works !!" > /init-contd/index.html
      sleep 30
    volumeMounts:
    - name: myvol
      mountPath: /init-contd

  volumes:
  - name: myvol
    emptyDir: {}
  hostNetwork: true
