apiVersion: v1
kind: Pod
metadata:
  name: ex2-tomcat
spec:
  containers:
  - name: ex2-tomcat
    image: tomcat
    ports:
    - containerPort: 8080

  initContainers:
  - name: init-con
    image: busybox
    command: ['sh','-c','sleep 60']

  hostNetwork: true
